services:
  - type: web
    name: azd-pdf-generator
    env: node
    plan: free # 如果你用的是免费方案，改成 starter/standard 如果你使用付费
    buildCommand: ./build.sh
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - index.js
        - build.sh
        - package.json
        - public/**
